name: Text-Stat CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  code-quality:  # 代码质量检查
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          pip install black ruff  # 明确安装代码检查工具
          pip install -r requirements.txt  # 安装项目依赖
      - run: black --check . && ruff check .  # 执行检查
  test:  # 自动化测试
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: echo "TEXT_API_KEY=${{ secrets.TEXT_API_KEY }}" > .env
      - run: pytest tests/test_main.py -v
  docker-build:  # 容器构建
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: text-stat-app:latest  # 确保此处无语法错误（如多余字符）