name: Text-Stat CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  code-quality:  # 代码质量检查
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          pip install black ruff
          pip install -r requirements.txt
      - run: black --check . && ruff check .

  test:  # 自动化测试（需与 code-quality 同级）
    needs: code-quality
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: echo "TEXT_API_KEY=${{ secrets.TEXT_API_KEY }}" > .env
      - run: cat .env  # 验证 .env 内容
      - run: pytest tests/test_main.py -v

  docker-build:  # 容器构建（需与 code-quality 同级）
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: text-stat-app:latest